### ISSUE TITLE
Ubuntu 20.10 followed docker requirements missing cmake dep?

### ISSUE THREAD

**Issue by jswhisperer** [petwu/nordvpn-gui#1]
```CMake Error at cmake/CodeQualityTools.cmake:46 (find_program):
  Could not find IWYU_TOOL_PY using the following names: iwyu_tool.py
Call Stack (most recent call first):
  CMakeLists.txt:20 (include)
```

**Comment by jswhisperer** [comment]
https://github.com/petwu/nordvpn-gui/blob/896998c9097cbe32119b9584b7d035bc4646ba7d/cmake/CodeQualityTools.cmake#L46

**Comment by jswhisperer** [comment]
I don't know python when I'm sober but I reckon the ```find_program``` isnt linking to include what you use correctly?

**Comment by jswhisperer** [comment]
I added iwyu to the path https://include-what-you-use.org/
no progress

**Comment by petwu** [comment]
I just push something (6e54f82) that removed the REQUIRED from those tools like iyqu, clang-tidy, etc., because they aren't necessary for building the application. Don't know yet, why `iwyu_tool.py` was not found, going to investigate that some time later.

Were you trying to use the Dockerfile to run the application? If so, I'm have to disappoint you for now. The Dockerfile was initially intended to run some checks (clang-tidy, iwyu, etc.) in a clean environment. I am probably going to change that some day, but currently I am working on some refactoring and some issues with other desktop environment (I mainly used KDE until now) ...

**Comment by jswhisperer** [comment]
@petwu hey thanks for the response and investigation. No wasn't trying run the Docker, just copying the deps since the setup instructions are light.
